// AUTO-GENERATED by scripts/gen-homepage-demo.ts — do not hand-edit.
// Real FYLYMPITCH ENGINE output for representative sample projects, computed
// offline against the live MASTER_DATA opportunity catalog (migration 005).
// Every score, count, readiness value and award below is genuine engine output
// from services/fylympitchEngine.ts — no fabricated or hand-tuned numbers.
//
// Regenerate after the catalog or engine changes:
//   npx tsx scripts/gen-homepage-demo.ts
//
export type DemoTier = "excellent" | "strong" | "possible";
export interface DemoMatch { name: string; typeLabel: string; country: string; award: string; deadline: string; score: number; tier: DemoTier; }
export interface DemoStage { label: string; status: "done" | "current" | "upcoming"; live: number; }
export interface DemoCategory { label: string; count: number; }
export interface DemoProject {
  title: string; genre: string; format: string; country: string; language: string;
  budgetLabel: string; seekingLabel: string; readiness: number; matchedSources: number;
  categories: DemoCategory[]; topMatches: DemoMatch[]; roadmap: DemoStage[]; ep: string;
}
export const DEMO_PROJECTS: DemoProject[] = [
  {
    "title": "SAMPLE FEATURE — COMEDY",
    "genre": "Comedy",
    "format": "feature",
    "country": "India",
    "language": "Hindi",
    "budgetLabel": "$2.5M",
    "seekingLabel": "$1.8M",
    "readiness": 90,
    "matchedSources": 51,
    "categories": [
      {
        "label": "Grants & funds",
        "count": 30
      },
      {
        "label": "Labs & residencies",
        "count": 14
      },
      {
        "label": "Markets & co-pro",
        "count": 7
      }
    ],
    "topMatches": [
      {
        "name": "Reborn India Screenwriters' Lab",
        "typeLabel": "Lab",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual; check website",
        "score": 99,
        "tier": "excellent"
      },
      {
        "name": "Uttar Pradesh Film Subsidy",
        "typeLabel": "Development Grant",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Apply before shoot; claim post-completion",
        "score": 99,
        "tier": "excellent"
      },
      {
        "name": "FTII Script Development",
        "typeLabel": "Lab",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual",
        "score": 99,
        "tier": "excellent"
      },
      {
        "name": "KOFIC — Korea Film Council",
        "typeLabel": "Development Fund",
        "country": "South Korea",
        "award": "Up to $2.0M",
        "deadline": "Multiple windows — check kofic.or.kr",
        "score": 98,
        "tier": "excellent"
      }
    ],
    "roadmap": [
      {
        "label": "Script",
        "status": "done",
        "live": 0
      },
      {
        "label": "Labs",
        "status": "current",
        "live": 14
      },
      {
        "label": "Co-production",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Grants",
        "status": "upcoming",
        "live": 30
      },
      {
        "label": "Investors",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Production",
        "status": "upcoming",
        "live": 7
      }
    ],
    "ep": "\"SAMPLE FEATURE — COMEDY\" scores 99/100 against \"Reborn India Screenwriters' Lab\", its strongest current match. The project profile is well-rounded for this category."
  },
  {
    "title": "SAMPLE FEATURE — DRAMA",
    "genre": "Drama",
    "format": "feature",
    "country": "India",
    "language": "Malayalam",
    "budgetLabel": "$1.5M",
    "seekingLabel": "$1.1M",
    "readiness": 90,
    "matchedSources": 9,
    "categories": [
      {
        "label": "Markets & co-pro",
        "count": 9
      }
    ],
    "topMatches": [
      {
        "name": "Asia TV Forum & Market (ATF)",
        "typeLabel": "Film Market",
        "country": "Singapore",
        "award": "Amount varies",
        "deadline": "Annual; December (Singapore)",
        "score": 83,
        "tier": "strong"
      },
      {
        "name": "Berlinale Co-Production Market",
        "typeLabel": "Film Market",
        "country": "Germany",
        "award": "Amount varies",
        "deadline": "Annual — Feb (during Berlinale). Applications open ~Oct.",
        "score": 78,
        "tier": "strong"
      },
      {
        "name": "Cannes Marché du Film",
        "typeLabel": "Film Market",
        "country": "France",
        "award": "Amount varies",
        "deadline": "Annual — May. Registration opens ~Feb each year.",
        "score": 78,
        "tier": "strong"
      },
      {
        "name": "Docedge Kolkata",
        "typeLabel": "Film Market",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual — March. Applications open ~Nov. Check docedgekolkata.com",
        "score": 73,
        "tier": "possible"
      }
    ],
    "roadmap": [
      {
        "label": "Script",
        "status": "done",
        "live": 0
      },
      {
        "label": "Labs",
        "status": "done",
        "live": 0
      },
      {
        "label": "Co-production",
        "status": "current",
        "live": 0
      },
      {
        "label": "Grants",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Investors",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Production",
        "status": "upcoming",
        "live": 9
      }
    ],
    "ep": "\"SAMPLE FEATURE — DRAMA\" scores 83/100 against \"Asia TV Forum & Market (ATF)\", its strongest current match. The project profile is well-rounded for this category."
  },
  {
    "title": "SAMPLE FEATURE — DOCUMENTARY",
    "genre": "Documentary",
    "format": "documentary",
    "country": "India",
    "language": "English",
    "budgetLabel": "$200K",
    "seekingLabel": "$150K",
    "readiness": 75,
    "matchedSources": 64,
    "categories": [
      {
        "label": "Grants & funds",
        "count": 42
      },
      {
        "label": "Labs & residencies",
        "count": 12
      },
      {
        "label": "Markets & co-pro",
        "count": 10
      }
    ],
    "topMatches": [
      {
        "name": "Screen Australia Development Funding",
        "typeLabel": "Development Fund",
        "country": "Australia",
        "award": "Up to $370K",
        "deadline": "Rolling (4 rounds/year)",
        "score": 99,
        "tier": "excellent"
      },
      {
        "name": "KOFIC — Korea Film Council",
        "typeLabel": "Development Fund",
        "country": "South Korea",
        "award": "Up to $2.0M",
        "deadline": "Multiple windows — check kofic.or.kr",
        "score": 98,
        "tier": "excellent"
      },
      {
        "name": "Film Victoria Australia",
        "typeLabel": "Development Fund",
        "country": "Australia",
        "award": "Up to $2.0M",
        "deadline": "Rolling applications — film.vic.gov.au",
        "score": 98,
        "tier": "excellent"
      },
      {
        "name": "Fonds Francophone",
        "typeLabel": "Development Fund",
        "country": "Europe",
        "award": "Up to $220K",
        "deadline": "Annual",
        "score": 96,
        "tier": "excellent"
      }
    ],
    "roadmap": [
      {
        "label": "Script",
        "status": "done",
        "live": 0
      },
      {
        "label": "Labs",
        "status": "current",
        "live": 12
      },
      {
        "label": "Co-production",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Grants",
        "status": "upcoming",
        "live": 42
      },
      {
        "label": "Investors",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Production",
        "status": "upcoming",
        "live": 10
      }
    ],
    "ep": "\"SAMPLE FEATURE — DOCUMENTARY\" scores 99/100 against \"Screen Australia Development Funding\", its strongest current match. The project profile is well-rounded for this category."
  }
];
