// AUTO-GENERATED by scripts/gen-homepage-demo.ts — do not hand-edit.
// Real FYLYMPITCH ENGINE output for representative sample projects, computed
// offline against the live MASTER_DATA opportunity catalog (migration 005).
// Every score, count, readiness value and award below is genuine engine output
// from services/fylympitchEngine.ts — no fabricated or hand-tuned numbers.
//
// Regenerate after the catalog or engine changes:
//   npx tsx scripts/gen-homepage-demo.ts
//
export type DemoTier = "excellent" | "strong" | "possible";
export interface DemoMatch { name: string; typeLabel: string; country: string; award: string; deadline: string; score: number; tier: DemoTier; }
export interface DemoStage { label: string; status: "done" | "current" | "upcoming"; live: number; }
export interface DemoCategory { label: string; count: number; }
export interface DemoProject {
  title: string; genre: string; format: string; country: string; language: string;
  /** Illustrative, for the sample card. Not engine output. */
  logline: string;
  budgetLabel: string; seekingLabel: string; readiness: number; matchedSources: number;
  categories: DemoCategory[]; topMatches: DemoMatch[]; roadmap: DemoStage[]; ep: string;
}
export const DEMO_PROJECTS: DemoProject[] = [
  {
    "title": "SAMPLE FEATURE — COMEDY",
    "genre": "Comedy",
    "format": "feature",
    "country": "India",
    "language": "Hindi",
    "logline": "Three strangers share a battered van across the country, and none of them is going where they said.",
    "budgetLabel": "$2.5M",
    "seekingLabel": "$1.8M",
    "readiness": 90,
    "matchedSources": 57,
    "categories": [
      {
        "label": "Grants & funds",
        "count": 33
      },
      {
        "label": "Labs & residencies",
        "count": 16
      },
      {
        "label": "Markets & co-pro",
        "count": 8
      }
    ],
    "topMatches": [
      {
        "name": "Reborn India Screenwriters' Lab",
        "typeLabel": "Lab",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual; check website",
        "score": 84,
        "tier": "excellent"
      },
      {
        "name": "Uttar Pradesh Film Subsidy",
        "typeLabel": "Development Grant",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Apply before shoot; claim post-completion",
        "score": 84,
        "tier": "excellent"
      },
      {
        "name": "FTII Script Development",
        "typeLabel": "Lab",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual",
        "score": 84,
        "tier": "excellent"
      },
      {
        "name": "Screen Australia Development Funding",
        "typeLabel": "Development Fund",
        "country": "Australia",
        "award": "Up to $370K",
        "deadline": "Rolling (4 rounds/year)",
        "score": 78,
        "tier": "excellent"
      }
    ],
    "roadmap": [
      {
        "label": "Script",
        "status": "done",
        "live": 0
      },
      {
        "label": "Labs",
        "status": "current",
        "live": 16
      },
      {
        "label": "Co-production",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Grants",
        "status": "upcoming",
        "live": 33
      },
      {
        "label": "Investors",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Production",
        "status": "upcoming",
        "live": 8
      }
    ],
    "ep": "\"SAMPLE FEATURE — COMEDY\" scores 84/100 against \"Reborn India Screenwriters' Lab\", its strongest current match. The project profile is well-rounded for this category."
  },
  {
    "title": "SAMPLE FEATURE — DRAMA",
    "genre": "Drama",
    "format": "feature",
    "country": "India",
    "language": "Malayalam",
    "logline": "A fisherman returns to a coast he left thirty years ago, to a daughter who has built a life without him.",
    "budgetLabel": "$1.5M",
    "seekingLabel": "$1.1M",
    "readiness": 90,
    "matchedSources": 10,
    "categories": [
      {
        "label": "Markets & co-pro",
        "count": 10
      }
    ],
    "topMatches": [
      {
        "name": "Asia TV Forum & Market (ATF)",
        "typeLabel": "Film Market",
        "country": "Singapore",
        "award": "Amount varies",
        "deadline": "Annual; December (Singapore)",
        "score": 68,
        "tier": "strong"
      },
      {
        "name": "Warsaw Industry Days (WID)",
        "typeLabel": "Film Market",
        "country": "Poland",
        "award": "Amount varies",
        "deadline": "Annual; October",
        "score": 61,
        "tier": "possible"
      },
      {
        "name": "Docedge Kolkata",
        "typeLabel": "Film Market",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual — March. Applications open ~Nov. Check docedgekolkata.com",
        "score": 58,
        "tier": "possible"
      },
      {
        "name": "NFDC Film Bazaar — IFFI Goa",
        "typeLabel": "Film Market",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual — November (IFFI Goa). Applications open ~Aug.",
        "score": 58,
        "tier": "possible"
      }
    ],
    "roadmap": [
      {
        "label": "Script",
        "status": "done",
        "live": 0
      },
      {
        "label": "Labs",
        "status": "done",
        "live": 0
      },
      {
        "label": "Co-production",
        "status": "current",
        "live": 0
      },
      {
        "label": "Grants",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Investors",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Production",
        "status": "upcoming",
        "live": 10
      }
    ],
    "ep": "\"SAMPLE FEATURE — DRAMA\" scores 68/100 against \"Asia TV Forum & Market (ATF)\", its strongest current match. The project profile is well-rounded for this category."
  },
  {
    "title": "SAMPLE FEATURE — DOCUMENTARY",
    "genre": "Documentary",
    "format": "documentary",
    "country": "India",
    "language": "English",
    "logline": "The last three projectionists of a dying single-screen circuit, and the films they refuse to stop showing.",
    "budgetLabel": "$200K",
    "seekingLabel": "$150K",
    "readiness": 75,
    "matchedSources": 61,
    "categories": [
      {
        "label": "Grants & funds",
        "count": 40
      },
      {
        "label": "Labs & residencies",
        "count": 13
      },
      {
        "label": "Markets & co-pro",
        "count": 8
      }
    ],
    "topMatches": [
      {
        "name": "Screen Australia Development Funding",
        "typeLabel": "Development Fund",
        "country": "Australia",
        "award": "Up to $370K",
        "deadline": "Rolling (4 rounds/year)",
        "score": 89,
        "tier": "excellent"
      },
      {
        "name": "Fonds Francophone",
        "typeLabel": "Development Fund",
        "country": "Europe",
        "award": "Up to $220K",
        "deadline": "Annual",
        "score": 79,
        "tier": "excellent"
      },
      {
        "name": "Docedge Kolkata",
        "typeLabel": "Film Market",
        "country": "India",
        "award": "Amount varies",
        "deadline": "Annual — March. Applications open ~Nov. Check docedgekolkata.com",
        "score": 78,
        "tier": "excellent"
      },
      {
        "name": "Whicker's World Foundation",
        "typeLabel": "Development Fund",
        "country": "United Kingdom",
        "award": "Amount varies",
        "deadline": "Annual (spring)",
        "score": 77,
        "tier": "strong"
      }
    ],
    "roadmap": [
      {
        "label": "Script",
        "status": "done",
        "live": 0
      },
      {
        "label": "Labs",
        "status": "current",
        "live": 13
      },
      {
        "label": "Co-production",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Grants",
        "status": "upcoming",
        "live": 40
      },
      {
        "label": "Investors",
        "status": "upcoming",
        "live": 0
      },
      {
        "label": "Production",
        "status": "upcoming",
        "live": 8
      }
    ],
    "ep": "\"SAMPLE FEATURE — DOCUMENTARY\" scores 89/100 against \"Screen Australia Development Funding\", its strongest current match. The project profile is well-rounded for this category."
  }
];
