-- ============================================================
-- FYLYMPITCH — Migration 032: Fill empty opportunity categories
-- Run once in Supabase SQL Editor.
--
-- Adds genuine industry data across 5 previously empty categories:
-- • Early Financing (crowdfunding)         — 11 entries
-- • Production (production_company/studio) — 11 entries
-- • Private Financing (investor)           — 10 entries
-- • Release & Distribution (distribution)  — 12 entries
-- • Tax Incentives (tax_incentive)         — 14 entries
-- • Buyers & Sales additions (sales_agent/pre_sale) — 12 entries
-- Total: 70 new entries
-- ============================================================

insert into public.opportunities (
  title, opp_type, description, country, region,
  genres, formats, stages, languages,
  min_budget_usd, max_budget_usd, max_award_usd,
  deadline, url, is_active,
  career_stages, match_weight,
  gender_focus, copro_required, festival_affiliated, ott_affiliated,
  contact_email, contact_phone, key_person, app_link, deadline_note
) values

-- ============================================================
-- EARLY FINANCING — CROWDFUNDING (11)
-- ============================================================

('Kickstarter Film & Video', 'crowdfunding',
  'The world''s largest crowdfunding platform for creative projects. Film & Video is one of Kickstarter''s most active categories. Uses all-or-nothing funding — projects only receive funds if they reach their goal. Over 31,000 successful film campaigns to date.',
  'United States', null,
  '{}', '{"feature","documentary","short","animation","series"}', '{"development","pre_production"}', '{}',
  null, null, null,
  null, 'https://www.kickstarter.com/films', true,
  '{"debut","second_film","established","veteran"}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.kickstarter.com/start', 'Rolling — campaigns set own deadlines'),

('Indiegogo Film', 'crowdfunding',
  'Global crowdfunding platform offering both fixed and flexible funding models. Flexible funding allows filmmakers to keep whatever they raise, even without hitting the target goal. Strong international reach across 235 countries and territories.',
  'United States', null,
  '{}', '{"feature","documentary","short","animation","series"}', '{"development","pre_production"}', '{}',
  null, null, null,
  null, 'https://www.indiegogo.com', true,
  '{"debut","second_film","established","veteran"}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.indiegogo.com/start-a-campaign', 'Rolling — campaigns set own deadlines'),

('Seed&Spark', 'crowdfunding',
  'The leading film-specific crowdfunding platform with an integrated audience-building and streaming distribution pathway. No platform fee for filmmakers — relies on backer tips. Boasts a 75% success rate for campaigns that reach 80% of their goal. Patrons Circle connects emerging filmmakers with industry veterans.',
  'United States', null,
  '{}', '{"feature","documentary","short"}', '{"development","pre_production"}', '{"English"}',
  null, 150000, null,
  null, 'https://www.seedandspark.com', true,
  '{"debut","second_film","established"}', 'high',
  null, false, false, true,
  null, null, null, 'https://www.seedandspark.com/fund/create', 'Rolling — campaigns set own deadlines'),

('Ulule', 'crowdfunding',
  'Europe''s leading crowdfunding platform for creative projects, operating in 14 languages. Offers coaching from a dedicated team and a multilingual interface for pan-European campaigns. Particularly strong in France, Belgium, Spain and Italy.',
  null, 'Europe',
  '{}', '{"feature","documentary","short","animation"}', '{"development","pre_production"}', '{}',
  null, null, null,
  null, 'https://www.ulule.com', true,
  '{"debut","second_film","established"}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.ulule.com/projects/create/', 'Rolling — campaigns set own deadlines'),

('Touscoprod', 'crowdfunding',
  'French crowdfunding platform created exclusively for film and audiovisual projects. Enables filmmakers to raise funds, collaborate with professionals, and access a network of partner organisations. Offers reward-based crowdfunding alongside co-production opportunities.',
  'France', null,
  '{}', '{"feature","documentary","short","animation"}', '{"development","pre_production"}', '{"French"}',
  null, null, null,
  null, 'https://www.touscoprod.com', true,
  '{"debut","second_film","established"}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.touscoprod.com', 'Rolling — campaigns set own deadlines'),

('Pozible', 'crowdfunding',
  'Australia''s leading crowdfunding platform for creative and community projects. Strong film category with all-or-nothing and flexible funding models. Regional presence in Australia, New Zealand and Southeast Asia.',
  'Australia', 'Asia-Pacific',
  '{}', '{"feature","documentary","short","animation"}', '{"development","pre_production"}', '{}',
  null, null, null,
  null, 'https://www.pozible.com', true,
  '{"debut","second_film","established"}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.pozible.com/create', 'Rolling — campaigns set own deadlines'),

('Crowdfunder UK', 'crowdfunding',
  'The UK''s most popular crowdfunding platform, supporting creative projects with reward-based and equity funding options. Partnered with major UK foundations and councils, offering matched-funding programmes for qualifying film projects.',
  'United Kingdom', null,
  '{}', '{"feature","documentary","short"}', '{"development","pre_production"}', '{"English"}',
  null, null, null,
  null, 'https://www.crowdfunder.co.uk', true,
  '{"debut","second_film","established"}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.crowdfunder.co.uk/start-fundraising', 'Rolling — campaigns set own deadlines'),

('Wishberry', 'crowdfunding',
  'India''s pioneering crowdfunding platform for creative projects, with a strong focus on independent cinema. Has helped fund over 1,000 creative projects across South Asia. Offers campaign coaching and marketing support tailored for Indian audiences.',
  'India', 'South Asia',
  '{}', '{"feature","documentary","short"}', '{"development","pre_production"}', '{}',
  null, null, null,
  null, 'https://www.wishberry.in', true,
  '{"debut","second_film"}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.wishberry.in/launch/', 'Rolling — campaigns set own deadlines'),

('Goteo', 'crowdfunding',
  'Social crowdfunding platform based in Spain, focused on projects with a positive social, cultural or educational impact. Offers matched funding through a network of public and private partners. Particularly suitable for documentary and social-issue films.',
  'Spain', 'Europe',
  '{"Documentary"}', '{"documentary","short"}', '{"development","pre_production"}', '{}',
  null, null, null,
  null, 'https://en.goteo.org', true,
  '{"debut","second_film","established"}', 'low',
  null, false, false, false,
  null, null, null, 'https://en.goteo.org/project/create', 'Rolling — campaigns set own deadlines'),

('Slated', 'crowdfunding',
  'Professional film financing marketplace that combines investor matchmaking with script scoring and project analytics. Connects filmmakers with a curated network of accredited investors. Projects with Slated Score of 75+ attract the highest investor interest. Has financed films starring Samuel L. Jackson, amongst others.',
  'United States', null,
  '{}', '{"feature","documentary"}', '{"development","pre_production","production"}', '{"English"}',
  100000, 10000000, null,
  null, 'https://www.slated.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, false,
  null, null, null, 'https://www.slated.com/join', 'Rolling — ongoing investor matching'),

('Patreon for Filmmakers', 'crowdfunding',
  'Membership platform enabling filmmakers to build a sustainable recurring income from fans and supporters. Ideal for documentary series, behind-the-scenes access, and episodic content. Creators keep 88-95% of earnings after fees. Strong for established filmmakers with existing audiences.',
  'United States', null,
  '{}', '{"documentary","series","short"}', '{"development","pre_production","production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.patreon.com', true,
  '{"established","veteran"}', 'low',
  null, false, false, false,
  null, null, null, 'https://www.patreon.com/create', 'Rolling — ongoing membership model'),

-- ============================================================
-- PRODUCTION — PRODUCTION COMPANIES & STUDIOS (11)
-- ============================================================

('Film4 Productions', 'production_company',
  'The film financing and production arm of Channel 4 (UK). Funds and co-produces distinctive, ambitious films that reflect the diversity of UK culture. Credits include Trainspotting, Slumdog Millionaire, 12 Years a Slave, and Aftersun. Accepts unsolicited treatments through agents and producers.',
  'United Kingdom', null,
  '{"Drama","Documentary","Thriller","Comedy"}', '{"feature","documentary"}', '{"development","production"}', '{"English"}',
  null, 15000000, null,
  null, 'https://www.film4.com/productions', true,
  '{"debut","second_film","established","veteran"}', 'high',
  null, false, true, true,
  'film4productions@channel4.co.uk', null, null, 'https://www.film4.com/productions', 'Rolling — accepts submissions year-round'),

('BBC Films', 'production_company',
  'BBC Films co-produces and develops distinctive, original films for cinema and BBC broadcast. Has backed films including Pride, Paddington, and The Favourite. Primarily UK talent but open to international co-productions. Works with both established filmmakers and first-time feature directors.',
  'United Kingdom', null,
  '{"Drama","Documentary","Comedy"}', '{"feature","documentary"}', '{"development","production"}', '{"English"}',
  null, 10000000, null,
  null, 'https://www.bbc.co.uk/commissioning/bbcfilms', true,
  '{"debut","second_film","established","veteran"}', 'high',
  null, false, true, true,
  null, null, 'Rose Garnett (Director)', 'https://www.bbc.co.uk/commissioning/bbcfilms', 'Rolling — accepts submissions via producers and agents'),

('Participant Media', 'production_company',
  'US production company focused on entertainment that inspires social change. Credits include Roma, Spotlight, An Inconvenient Truth, and Green Book. Backs documentaries and narrative films with strong social, political and environmental themes. Seeks projects with purpose-driven narratives.',
  'United States', null,
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"development","production"}', '{}',
  null, null, null,
  null, 'https://www.participant.com', true,
  '{"established","veteran"}', 'medium',
  null, false, true, true,
  null, null, null, 'https://www.participant.com', 'Rolling — via agent/producer submission'),

('Mubi', 'studio',
  'Global arthouse streaming platform and film production company. Has co-produced and distributed films by Ryûsuke Hamaguchi, Pablo Larraín, Joanna Hogg and many other leading auteurs. Raised $100M from Sequoia Capital in 2025 at a $1B valuation. Actively co-produces and acquires distinctive art cinema internationally.',
  'United Kingdom', null,
  '{"Drama"}', '{"feature","documentary"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://mubi.com/en/films', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, true,
  'hello@mubi.com', null, 'Efe Cakarel (Founder)', 'https://mubi.com/en/films', 'Rolling — open to pitches and completed films'),

('A24', 'studio',
  'Acclaimed independent studio and distributor known for bold, director-led cinema. Credits include Everything Everywhere All at Once, Hereditary, Moonlight, and The Whale. Produces, finances, and distributes approximately 15 features per year. Seeks original, distinctive projects with strong directorial vision.',
  'United States', null,
  '{"Drama","Horror","Comedy","Thriller"}', '{"feature"}', '{"development","production"}', '{}',
  null, null, null,
  null, 'https://a24films.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, false,
  null, null, null, 'https://a24films.com', 'Rolling — via agent/producer submission only'),

('Blumhouse Productions', 'production_company',
  'Leading US production company specialising in micro-budget and mid-budget genre films. Pioneered the "micro-budget, massive returns" model with films like Paranormal Activity, Get Out, and The Purge franchise. Actively seeks genre scripts from emerging filmmakers. Blumhouse Television also produces limited series.',
  'United States', null,
  '{"Horror","Thriller","Sci-Fi"}', '{"feature","series"}', '{"development","production"}', '{"English"}',
  null, 5000000, null,
  null, 'https://www.blumhouse.com', true,
  '{"debut","second_film","established"}', 'high',
  null, false, false, true,
  null, null, 'Jason Blum (Founder)', 'https://www.blumhouse.com', 'Rolling — active script submissions via agents'),

('Working Title Films', 'production_company',
  'One of the UK''s most successful production companies, backed by Universal. Known for Four Weddings and a Funeral, Love Actually, Atonement, and Les Misérables. Produces high-quality commercial and prestige cinema with international distribution reach. Works primarily through agent submissions.',
  'United Kingdom', null,
  '{"Drama","Comedy","Romance","Thriller"}', '{"feature"}', '{"development","production"}', '{"English"}',
  2000000, null, null,
  null, 'https://www.workingtitlefilms.com', true,
  '{"established","veteran"}', 'medium',
  null, false, true, false,
  null, null, 'Tim Bevan & Eric Fellner (Co-Chairs)', 'https://www.workingtitlefilms.com', 'Rolling — via agent submission'),

('Bac Films', 'production_company',
  'French independent production and sales company known for ambitious auteur cinema. Has produced films by Lars von Trier, Gaspar Noé, and Bertrand Bonello. Actively seeks co-productions with European and international partners. Strong presence at Cannes, Berlinale and Venice.',
  'France', 'Europe',
  '{"Drama","Thriller"}', '{"feature"}', '{"development","production"}', '{"French"}',
  null, null, null,
  null, 'https://www.bacfilms.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, true, true, false,
  'contact@bacfilms.com', null, null, 'https://www.bacfilms.com', 'Rolling — accepts co-production proposals year-round'),

('Wild Bunch', 'production_company',
  'Leading European film group combining production, international sales and distribution. Co-produces and acquires films across Europe and internationally. Credits include The Artist, Amour, and Holy Motors. Major presence at Cannes, EFM and AFM.',
  'France', 'Europe',
  '{"Drama","Thriller","Comedy","Documentary"}', '{"feature","documentary"}', '{"development","production"}', '{}',
  500000, null, null,
  null, 'https://www.wildbunch.eu', true,
  '{"second_film","established","veteran"}', 'high',
  null, true, true, true,
  'contact@wildbunch.eu', null, null, 'https://www.wildbunch.eu', 'Rolling — via agent or producer submission'),

('Film Nation Entertainment', 'production_company',
  'US production, finance and sales company with a track record of Oscar-winning prestige cinema. Credits include The Big Sick, Arrival, Knives Out and Widows. Provides gap financing, pre-sales and full equity. Strong relationships with international distributors and streaming platforms.',
  'United States', null,
  '{"Drama","Thriller","Comedy"}', '{"feature"}', '{"development","production"}', '{"English"}',
  2000000, null, null,
  null, 'https://wearefilmnation.com', true,
  '{"established","veteran"}', 'high',
  null, false, true, true,
  null, null, 'Glen Basner (CEO)', 'https://wearefilmnation.com', 'Rolling — via agent or producer submission'),

('XYZ Films', 'production_company',
  'US production company and international sales agency specialising in genre film. Credits include The Raid, Mandy, and Brawl in Cell 99. Actively seeks ambitious genre projects from both established and emerging filmmakers. Strong relationships with international festival circuit.',
  'United States', null,
  '{"Action","Horror","Thriller","Sci-Fi"}', '{"feature"}', '{"development","production"}', '{}',
  null, 10000000, null,
  null, 'https://xyzfilms.com', true,
  '{"debut","second_film","established"}', 'medium',
  null, false, true, false,
  null, null, null, 'https://xyzfilms.com/contact/', 'Rolling — accepts submissions via producers'),

-- ============================================================
-- PRIVATE FINANCING — INVESTORS (10)
-- ============================================================

('Ingenious Media', 'investor',
  'One of the world''s largest specialist media investment managers, with over $10 billion invested in more than 200 films. Credits include Avatar, the X-Men franchise, and Blinded by the Light. Provides co-financing and equity investment for commercial films, primarily alongside major studios and established producers.',
  'United Kingdom', null,
  '{}', '{"feature"}', '{"production"}', '{}',
  5000000, null, null,
  null, 'https://www.ingeniousmedia.co.uk', true,
  '{"established","veteran"}', 'medium',
  null, false, false, false,
  'info@ingeniousmedia.co.uk', null, null, 'https://www.ingeniousmedia.co.uk', 'Rolling — for projects with major studio or established producer attachment'),

('Embankment Films', 'investor',
  'UK-based international sales and financing company. Provides equity and pre-sales for prestige independent films. Represents films at Cannes, EFM and AFM. Credits include Promising Young Woman, The Father, and Mothering Sunday. Works with director-driven projects with strong international appeal.',
  'United Kingdom', null,
  '{"Drama","Thriller"}', '{"feature"}', '{"development","production"}', '{}',
  1000000, null, null,
  null, 'https://embankmentfilms.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, false,
  'info@embankmentfilms.com', null, 'Tim Haslam & Hugo Grumbar (Co-MDs)', 'https://embankmentfilms.com', 'Rolling — accepts projects for EFM, Cannes and AFM'),

('Film Constellation', 'investor',
  'International sales and financing company focused on quality independent cinema. Co-produces and pre-sells films across Europe and internationally. Strong track record in co-production with Scandinavian, Eastern European and North African partners. Credits include Human Flow by Ai Weiwei.',
  'United Kingdom', 'Europe',
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"development","production"}', '{}',
  500000, null, null,
  null, 'https://www.filmconstellation.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, true, true, false,
  'info@filmconstellation.com', null, 'Fabien Westerhoff (CEO)', 'https://www.filmconstellation.com', 'Rolling — via producer or agent submission'),

('Cornerstone Films', 'investor',
  'Independent UK sales and financing company specialising in quality commercial cinema. Provides co-financing and pre-sales for director-driven features. Strong relationships with US independent distributors and European buyers. Credits include The Courier, Last Night in Soho and Good Luck to You, Leo Grande.',
  'United Kingdom', null,
  '{"Drama","Thriller","Comedy"}', '{"feature"}', '{"production"}', '{"English"}',
  1000000, null, null,
  null, 'https://cornerstonefilm.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, false,
  'info@cornerstonefilm.com', null, null, 'https://cornerstonefilm.com', 'Rolling — accepts submissions year-round'),

('Protagonist Pictures', 'investor',
  'London-based international sales and financing company. Provides pre-sales, co-financing and gap financing for quality independent features. Strong relationship with Sundance, Berlin and Cannes directors. Credits include I Am Not a Witch, Victoria, and Free Fire.',
  'United Kingdom', null,
  '{"Drama","Thriller","Comedy","Documentary"}', '{"feature","documentary"}', '{"development","production"}', '{}',
  500000, null, null,
  null, 'https://www.protagonistpictures.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, false,
  'info@protagonistpictures.com', null, null, 'https://www.protagonistpictures.com', 'Rolling — accepts submissions via producers and agents'),

('AGC Studios', 'investor',
  'Independent studio with co-financing pact with Ingenious Media providing $150M+. Finances, produces and sells a broad slate of commercial independent films. Credits include Voyagers, Greyhound and Deep Water. Seeks projects with commercial appeal and international distribution potential.',
  'United States', null,
  '{"Drama","Action","Thriller","Sci-Fi"}', '{"feature"}', '{"development","production"}', '{"English"}',
  5000000, null, null,
  null, 'https://agcstudios.com', true,
  '{"established","veteran"}', 'medium',
  null, false, false, true,
  null, null, 'Stuart Ford (CEO)', 'https://agcstudios.com', 'Rolling — via agent or producer submission'),

('Memento Films International', 'investor',
  'French international sales and co-financing company. Has co-financed and sold films by Joachim Trier, Xavier Giannoli, and Jacques Audiard. Strong European auteur focus with global distribution reach. Attends all major markets: Cannes, EFM, AFM.',
  'France', 'Europe',
  '{"Drama"}', '{"feature"}', '{"development","production"}', '{}',
  300000, null, null,
  null, 'https://www.memento-films.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, true, true, false,
  'international@memento-films.com', null, null, 'https://www.memento-films.com', 'Rolling — via producer or agent submission'),

('mk2 Films', 'investor',
  'International sales arm of the iconic French cinema group mk2. Finances, co-produces and sells premium arthouse cinema worldwide. Has recently expanded co-production activity with English-language projects. Credits include Kiyoshi Kurosawa, the Taviani Brothers, and Bertrand Blier films.',
  'France', 'Europe',
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"development","production"}', '{}',
  null, null, null,
  null, 'https://mk2films.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, true, true, false,
  null, null, 'Nathanael Karmitz (Co-CEO)', 'https://mk2films.com', 'Rolling — via producer or agent submission'),

('Film Angels', 'investor',
  'Silicon Valley-based angel investor group dedicated exclusively to independent film. First angel investor group of its kind, funding projects from $250K to $2M. Backs films with strong ROI potential and broad audience appeal. Provides mentorship and industry connections alongside capital.',
  'United States', null,
  '{}', '{"feature"}', '{"production"}', '{"English"}',
  250000, 2000000, null,
  null, 'https://filmangels.org', true,
  '{"second_film","established"}', 'low',
  null, false, false, false,
  'info@filmangels.org', null, null, 'https://filmangels.org', 'Rolling — applications reviewed quarterly'),

('Curzon Film (Acquisitions & Finance)', 'investor',
  'UK arthouse cinema and film company — cinemas, distribution and streaming. Acquired by Fortress Investment Group in 2024. Finances, acquires and distributes prestige independent films theatrically and via Curzon Home Cinema. Strong track record with European auteur cinema and Oscar contenders.',
  'United Kingdom', null,
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"production","completed"}', '{}',
  500000, null, null,
  null, 'https://www.curzon.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, true,
  null, null, null, 'https://www.curzon.com', 'Rolling — accepts acquisitions at major festivals and markets'),

-- ============================================================
-- RELEASE & DISTRIBUTION (12)
-- ============================================================

('Kino Lorber', 'distribution',
  'New York-based independent distributor releasing 35 theatrical titles annually under its Kino Lorber, Zeitgeist Films, and Kino Repertory banners. Library of 4,000+ titles distributed across theatrical, home entertainment, educational and streaming platforms including Criterion Channel, MUBI and Netflix. Three Academy Award nominations in five years.',
  'United States', null,
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://kinolorber.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, true,
  'acquisitions@kinolorber.com', null, 'Richard Lorber (President)', 'https://kinolorber.com/submit', 'Rolling — accepts submissions year-round'),

('Magnolia Pictures', 'distribution',
  'A leading independent film studio and distributor for 20+ years. Theatrical and home entertainment arm of the Wagner/Cuban Companies. Releases thought-provoking documentaries and edgy independent features for both global and domestic audiences. Strong festival acquisition track record at Sundance and Cannes.',
  'United States', null,
  '{"Drama","Documentary","Thriller","Comedy"}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://www.magnoliapictures.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, true,
  'acquisitions@magnoliapictures.com', null, null, 'https://www.magnoliapictures.com', 'Rolling — acquisitions at major festivals and markets'),

('Oscilloscope Laboratories', 'distribution',
  'New York independent distributor founded by Beastie Boys'' Adam Yauch. Prioritises unconventional storytelling and distributes films theatrically, on home video and streaming. Grand Jury Award winners at SXSW receive a private industry meeting with Oscilloscope. Known for discovering bold, festival circuit films.',
  'United States', null,
  '{"Drama","Comedy","Documentary","Horror"}', '{"feature","documentary"}', '{"completed"}', '{"English"}',
  null, null, null,
  null, 'https://www.oscilloscope.net', true,
  '{"debut","second_film","established"}', 'medium',
  null, false, true, false,
  'acquisitions@oscilloscope.net', null, null, 'https://www.oscilloscope.net', 'Rolling — accepts submissions and acquires at major festivals'),

('Gravitas Ventures', 'distribution',
  'Worldwide film distributor connecting filmmakers with a global audience of over a billion people across theatrical, VOD, SVOD, television and AVOD. Acquired by Shout! Studios in April 2025. Specialises in digital-first releases and has distributed thousands of independent features over 15+ years.',
  'United States', null,
  '{}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://www.gravitasventures.com', true,
  '{"debut","second_film","established","veteran"}', 'medium',
  null, false, false, true,
  'submissions@gravitasventures.com', null, null, 'https://www.gravitasventures.com/submit', 'Rolling — accepts submissions year-round'),

('Film Movement', 'distribution',
  'New York-based distributor specialising in award-winning foreign and independent films. Operates a subscription club and digital distribution across North America. Focuses on international cinema with festival credentials. Distributes approximately 24 films per year across theatrical, educational and streaming platforms.',
  'United States', null,
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://www.filmmovement.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, true,
  'acquisitions@filmmovement.com', null, null, 'https://www.filmmovement.com/submit', 'Rolling — accepts submissions year-round'),

('IFC Films', 'distribution',
  'Leading US independent distributor and premium cable network. Releases prestige independent and foreign films theatrically and across streaming platforms. Known for day-and-date theatrical/VOD releases. Part of AMC Networks. Strong festival acquisition track record.',
  'United States', null,
  '{"Drama","Comedy","Documentary","Horror","Thriller"}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://www.ifcfilms.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, true,
  'acquisitions@ifcfilms.com', null, null, 'https://www.ifcfilms.com', 'Rolling — acquisitions at major festivals and markets'),

('MUBI Distribution', 'distribution',
  'MUBI distributes handpicked films theatrically, on DVD and through its own streaming platform in 190 countries. Following its $100M Sequoia investment in 2025, MUBI has expanded its acquisitions and co-production activity globally. Focuses on arthouse and auteur cinema from emerging and established directors.',
  'United Kingdom', null,
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"production","completed"}', '{}',
  null, null, null,
  null, 'https://mubi.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, true,
  'acquisitions@mubi.com', null, null, 'https://mubi.com', 'Rolling — acquisitions at Cannes, Venice, Berlin and Sundance'),

('Dogwoof', 'distribution',
  'UK-based documentary distributor and international sales agent. Releases award-winning documentaries theatrically in the UK and sells internationally. Credits include The Act of Killing, I Am Chris Farley and The Propaganda Game. Strong festival network and relationships with broadcaster buyers.',
  'United Kingdom', null,
  '{"Documentary"}', '{"documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://dogwoof.com', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, true,
  'submissions@dogwoof.com', null, null, 'https://dogwoof.com/submit', 'Rolling — accepts documentary submissions year-round'),

('Greenwich Entertainment', 'distribution',
  'New York-based independent distributor founded in 2017, specialising in distinctive theatrical-quality narrative and documentary features. Known for carefully curated slate with strong arthouse sensibility. Releases approximately 10-12 films per year across theatrical and digital platforms.',
  'United States', null,
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://www.greenwichentertainment.com', true,
  '{"second_film","established"}', 'medium',
  null, false, true, false,
  null, null, null, 'https://www.greenwichentertainment.com', 'Rolling — via agent or producer submission'),

('Roadside Attractions', 'distribution',
  'US independent distributor known for releasing commercially appealing indie films with broad audience reach. Credits include Manchester by the Sea, Hell or High Water, and The Whale. Expert at striking post-theatrical streaming deals with major platforms. Frequently acquires at Sundance and TIFF.',
  'United States', null,
  '{"Drama","Comedy","Thriller"}', '{"feature"}', '{"completed"}', '{"English"}',
  null, null, null,
  null, 'https://www.roadsideattractions.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, true,
  null, null, null, 'https://www.roadsideattractions.com', 'Rolling — acquisitions at major festivals'),

('Metrograph Pictures', 'distribution',
  'New York arthouse cinema and distributor known for championing films of exceptional visual and narrative ambition. Releases films theatrically and on its Metrograph at Home streaming platform. Closely tied to the international festival circuit. Strong curatorial sensibility.',
  'United States', null,
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://metrograph.com', true,
  '{"second_film","established","veteran"}', 'low',
  null, false, true, true,
  null, null, null, 'https://metrograph.com', 'Rolling — accepts submissions from producers and sales agents'),

('Picturehouse Entertainment', 'distribution',
  'UK-based independent distributor operating its own cinema chain of 25 venues. Releases arthouse, world cinema and crossover independent films across theatrical and digital. Strong track record distributing Oscar contenders and Palme d''Or winners. Part of the Cineworld Group.',
  'United Kingdom', null,
  '{"Drama","Documentary","Comedy"}', '{"feature","documentary"}', '{"completed"}', '{}',
  null, null, null,
  null, 'https://www.picturehouses.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, false,
  null, null, null, 'https://www.picturehouses.com', 'Rolling — accepts acquisitions at major festivals and markets'),

-- ============================================================
-- TAX INCENTIVES (14)
-- ============================================================

('UK Audio-Visual Expenditure Credit (AVEC)', 'tax_incentive',
  'Replaced the old Film Tax Relief in January 2024. Offers a 34% credit on qualifying UK expenditure for films costing under £15M (net 25.5% after corporation tax) and 53% for limited budget films. Effective April 2025, VFX costs receive a 39% gross credit with the 80% cap removed. No upper budget limit. One of the most competitive incentive programmes globally.',
  'United Kingdom', null,
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.bfi.org.uk/get-funding-and-support/film-tax-relief', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.bfi.org.uk/get-funding-and-support/film-tax-relief', 'Rolling — claim after production completes'),

('France Tax Rebate for International Productions (TRIP)', 'tax_incentive',
  'Rebate of 30% on qualifying French expenditure, rising to 40% if French VFX expenses exceed €2M. Available to foreign productions spending in France. No annual cap. France''s 2025 budget confirmed TRIP is protected. Non-resident talent costs now qualify as spend, significantly expanding the benefit.',
  'France', null,
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.cnc.fr/professionnels/aides-et-financements/credit-dimpot-international', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.cnc.fr', 'Rolling — claim after production completes'),

('Ireland Section 481 Film Tax Credit', 'tax_incentive',
  'Base rate of 32%, rising to 40% for Irish independent productions with budgets under €20M (announced 2024, effective 2025). One of the world''s most competitive programmes. Eligible spend up to €50M. Strong English-language crew base, EU co-production access, and tax treaty network.',
  'Ireland', null,
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{"English"}',
  null, null, null,
  null, 'https://www.revenue.ie/en/companies-and-charities/reliefs-and-exemptions/film-relief/index.aspx', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.revenue.ie', 'Rolling — claim after production completes'),

('Belgium Tax Shelter', 'tax_incentive',
  'Provides a 42% tax exemption for Belgian investors who finance qualifying audiovisual works. Among Europe''s most generous incentive structures. Strong co-production tradition. Eligible for EU co-production frameworks. Brussels and Ghent are active production hubs.',
  'Belgium', 'Europe',
  '{}', '{"feature","documentary","animation","series"}', '{"production"}', '{}',
  null, null, null,
  null, 'https://www.taxshelter.be', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.taxshelter.be', 'Rolling — structured with Belgian co-producer'),

('Germany DFFF (Deutscher Filmförderfonds)', 'tax_incentive',
  'Federal incentive offering a 30% rebate on qualifying German production expenditure (increased 2025). Extended for another year with increased rates and no diversity clause. Germany Production Matching Fund (GMPF) also offers 30%. Combined with regional Medienboard, FFF Bayern and other Länder funds.',
  'Germany', 'Europe',
  '{}', '{"feature","documentary","animation"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.ffa.de/foerderung-dfff.html', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.ffa.de', 'Rolling — claim with qualifying German expenditure'),

('Australia Location Offset', 'tax_incentive',
  'Increased from 16.5% to 30% in 2025 — the most aggressive incentive increase globally that year. Available to international productions spending in Australia. No annual cap and no sunset date. Additional regional incentives available in New South Wales (10%), Victoria (10%), Queensland (15%) and South Australia (10%).',
  'Australia', 'Asia-Pacific',
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.screenaustralia.gov.au/funding-and-support/producer-offset', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.screenaustralia.gov.au', 'Rolling — claim after production completes'),

('New Zealand Screen Production Grant', 'tax_incentive',
  'Offers 20% on qualifying New Zealand expenditure for international productions, rising to 25% for productions spending over NZD $30M. An additional 5% uplift for post-production. Known for world-class crew infrastructure, diverse locations, and efficient film commission support.',
  'New Zealand', 'Asia-Pacific',
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.screennz.co.nz/funding/large-budget-screen-production-grant', true,
  '{}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.screennz.co.nz', 'Rolling — application before principal photography'),

('Spain Canary Islands Film Incentive', 'tax_incentive',
  'Europe''s highest film tax rebate at 45-50% on qualifying expenditure in the Canary Islands. Mainland Spain offers 25-30%. Basque Country offers 35-70%. Navarre 35%. Diverse filming locations ranging from volcanic landscapes to colonial cities, desert and beaches.',
  'Spain', 'Europe',
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.gobiernodecanarias.org/hacienda/cice/', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://www.gobiernodecanarias.org', 'Rolling — structured before principal photography in Canary Islands'),

('Czech Republic Film Incentive', 'tax_incentive',
  'Refundable tax credit increased to 25% for standard productions (January 2025), with 35% for animation and digital productions. Cap nearly tripled to $19M in 2025. Prague is a rapidly growing VFX and post-production hub with competitive crews. Strong access to Eastern European locations.',
  'Czech Republic', 'Europe',
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.filmcommission.cz/film-incentives/', true,
  '{}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.filmcommission.cz', 'Rolling — apply before principal photography'),

('Hungary Film Tax Incentive', 'tax_incentive',
  '30% rebate on qualifying Hungarian expenditure with no cap in absolute value. Hungary has grown significantly as an international production hub over the past decade. Budapest has world-class studio infrastructure. Cultural test requires 24 of 32 points, primarily through production conditions.',
  'Hungary', 'Europe',
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.nfi.hu/en/incentives', true,
  '{}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.nfi.hu', 'Rolling — apply before principal photography'),

('Italy Tax Credit for Film', 'tax_incentive',
  '40% tax credit for Italian production companies on qualifying production expenditure. Foreign co-productions with Italian companies qualify. Italy offers exceptional locations, world-class crews and strong craft traditions in costume and set design. Rome, Venice and Sicily are popular production bases.',
  'Italy', 'Europe',
  '{}', '{"feature","documentary","animation"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.mibact.gov.it/it/cinema', true,
  '{}', 'medium',
  null, true, false, false,
  null, null, null, 'https://www.mibact.gov.it', 'Rolling — structured through Italian co-producer'),

('Malta Film Incentive', 'tax_incentive',
  '40% cash rebate on all qualifying expenditure in Malta, including non-resident above-the-line talent (one of few jurisdictions globally to include this). No minimum spend requirement. Malta Film Studios offers world-class Mediterranean water tanks. Gladiator II was partially filmed in Malta.',
  'Malta', 'Europe',
  '{}', '{"feature","documentary","animation"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://mfc.gov.mt/en/financial-incentives', true,
  '{}', 'high',
  null, false, false, false,
  null, null, null, 'https://mfc.gov.mt', 'Rolling — apply before principal photography'),

('Colombia Cash Rebate', 'tax_incentive',
  '35-40% cash rebate on qualifying Colombian expenditure. 2026 budget increased 49% to $90M — South America''s most competitive and fast-growing incentive. Diverse locations from Caribbean coastline to Andean mountains, Amazon jungle and colonial cities. Growing crew infrastructure.',
  'Colombia', 'Latin America',
  '{}', '{"feature","documentary","animation","series"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.procolombia.co/en/invest-in-colombia/film-sector', true,
  '{}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.procolombia.co', 'Rolling — apply before principal photography'),

('Morocco Cash Rebate', 'tax_incentive',
  '30% cash rebate on qualifying Moroccan expenditure. Gladiator II filmed extensively in Morocco alongside Malta. Marrakech, the Atlas Mountains and Saharan locations are popular. CCM (Centre Cinématographique Marocain) offers streamlined application process. Strong crew infrastructure built from decades of international production.',
  'Morocco', 'Africa',
  '{}', '{"feature","documentary","animation"}', '{"production","post_production"}', '{}',
  null, null, null,
  null, 'https://www.ccm.ma', true,
  '{}', 'medium',
  null, false, false, false,
  null, null, null, 'https://www.ccm.ma', 'Rolling — apply before principal photography in Morocco'),

-- ============================================================
-- BUYERS & SALES — SALES AGENTS & PRE-SALES (12)
-- ============================================================

('The Match Factory', 'sales_agent',
  'Cologne-based international sales company representing auteur cinema from around the world. Has sold films by Michael Haneke, Wim Wenders, and Yorgos Lanthimos. Cannes Competition and major festival regular. Represents filmmakers from over 40 countries. Active buyer of first and second features at development stage.',
  'Germany', 'Europe',
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://www.matchfactory.de', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, false,
  'info@matchfactory.de', '+49-221-539-7090', null, 'https://www.matchfactory.de/contact/', 'Rolling — via producer submission'),

('Wild Bunch International', 'sales_agent',
  'One of Europe''s leading international sales companies, handling a slate of 20-25 films per year. Represents major European and international directors. Strong presence at Cannes, EFM and AFM. Part of the Wild Bunch group which also includes production and distribution divisions.',
  'France', 'Europe',
  '{"Drama","Comedy","Thriller","Documentary"}', '{"feature","documentary"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://www.wildbunch.eu/sales', true,
  '{"second_film","established","veteran"}', 'high',
  null, false, true, false,
  'sales@wildbunch.eu', null, null, 'https://www.wildbunch.eu', 'Rolling — via producer submission at markets'),

('HanWay Films', 'sales_agent',
  'Independent British international sales, distribution and marketing company specialising in high-profile quality films. Founded 1998 by producer Jeremy Thomas. Now part of Cohen Media Group. Focuses on commercial prestige features by major international directors. Handles full international sales and distribution strategy.',
  'United Kingdom', null,
  '{"Drama","Thriller","Action"}', '{"feature"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://www.hanwayfilms.com', true,
  '{"established","veteran"}', 'medium',
  null, false, true, false,
  'info@hanwayfilms.com', '+44-20-7290-0750', 'Nicole Mackey (Director of Sales)', 'https://www.hanwayfilms.com/contact/', 'Rolling — accepts projects at all major markets'),

('mk2 Films International Sales', 'sales_agent',
  'International sales arm of the iconic French cinema group mk2. Represents auteur and arthouse films at all major festivals and markets. Expanding into English-language co-productions. 2025 Cannes slate included films with Cate Blanchett and Ben Stiller. Strong buyer relationships across all territories.',
  'France', 'Europe',
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://mk2films.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, false,
  'international@mk2.fr', null, null, 'https://mk2films.com/contact/', 'Rolling — via producer submission at Cannes, EFM, AFM'),

('Celluloid Dreams', 'sales_agent',
  'Paris-based international sales company specialising in arthouse and world cinema. Represents films from Asia, Latin America, Middle East and Eastern Europe alongside European productions. Strong track record at Cannes Un Certain Regard and Venice Horizons. Open to first and second features.',
  'France', 'Europe',
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'http://celluloid-dreams.com', true,
  '{"debut","second_film","established"}', 'high',
  null, false, true, false,
  'info@celluloid-dreams.com', '+33-1-4970-0370', null, 'http://celluloid-dreams.com/contact/', 'Rolling — actively seeks world cinema and debut features'),

('Cercamon', 'sales_agent',
  'International sales company focused on emerging talent and quality arthouse cinema. Specialises in representing first and second features at Cannes, Berlin, Venice and Sundance. Strong relationships with arthouse distributors in Europe and North America. Active scout for debut features worldwide.',
  'France', 'Europe',
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"production","completed"}', '{}',
  null, null, null,
  null, 'https://www.cercamon.biz', true,
  '{"debut","second_film"}', 'high',
  null, false, true, false,
  'contact@cercamon.biz', null, null, 'https://www.cercamon.biz/contact/', 'Rolling — specialises in debut and second features'),

('Beta Cinema', 'sales_agent',
  'Munich-based international sales company representing quality commercial and crossover films from Europe and beyond. Part of the Beta Group. Strong in Germany and Central European markets. Also handles pre-sales financing for upcoming productions. Represents approximately 20 films per year.',
  'Germany', 'Europe',
  '{"Drama","Thriller","Comedy","Documentary"}', '{"feature","documentary"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://www.betacinema.com', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, false,
  'info@betacinema.com', '+49-89-67-34-700', null, 'https://www.betacinema.com/contact/', 'Rolling — via producer submission'),

('The Open Reel', 'sales_agent',
  'Barcelona-based international sales agent focusing on world cinema, particularly from Southern Europe, Latin America, Middle East and Asia. Champions global diversity in cinema. Attends all major markets including Cannes, EFM, AFM and Toronto. Open to completed films and films in production.',
  'Spain', 'Europe',
  '{"Drama","Documentary"}', '{"feature","documentary"}', '{"production","completed"}', '{}',
  null, null, null,
  null, 'https://theopenreel.com', true,
  '{"debut","second_film","established"}', 'medium',
  null, false, true, false,
  'info@theopenreel.com', null, null, 'https://theopenreel.com/submit/', 'Rolling — accepts submissions year-round'),

('Kinology', 'sales_agent',
  'Paris-based international sales company with a strong roster of genre, thriller and prestige drama. Co-founded by former Focus Features and Studiocanal executives. Has represented films at Cannes Competition and key sidebars. Growing co-production arm for English-language projects.',
  'France', 'Europe',
  '{"Drama","Thriller","Action","Comedy"}', '{"feature"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://www.kinology.eu', true,
  '{"second_film","established","veteran"}', 'medium',
  null, false, true, false,
  'info@kinology.eu', null, null, 'https://www.kinology.eu/contact/', 'Rolling — via producer submission at markets'),

('Charades', 'sales_agent',
  'Paris-based independent sales company that co-produces, finances and sells a curated slate of ambitious films. Strong festival presence at Cannes, Berlin and Sundance. Credits include films by Xavier Dolan and Nadav Lapid. Provides pre-sales and financing support alongside international sales representation.',
  'France', 'Europe',
  '{"Drama","Documentary","Comedy"}', '{"feature","documentary"}', '{"development","production","completed"}', '{}',
  null, null, null,
  null, 'https://charades.eu', true,
  '{"debut","second_film","established","veteran"}', 'high',
  null, false, true, false,
  'info@charades.eu', null, null, 'https://charades.eu/contact/', 'Rolling — via producer submission'),

('Canal+ International (Pre-Sales)', 'pre_sale',
  'French pay-TV group with over 20 million subscribers worldwide. Canal+ is a leading European commissioner and pre-buyer of independent films and series. Pre-buys French and international features across all genres for French-speaking territories. Also produces original content through Studio Canal.',
  'France', 'Europe',
  '{"Drama","Thriller","Comedy","Action","Documentary"}', '{"feature","series"}', '{"development","production"}', '{"French"}',
  500000, null, null,
  null, 'https://www.canalplus.com', true,
  '{"established","veteran"}', 'medium',
  null, false, false, true,
  null, null, null, 'https://www.canalplus.com', 'Rolling — pre-sales negotiated at EFM, Cannes and AFM'),

('ZDF/Arte (Co-Production & Pre-Sale)', 'pre_sale',
  'Joint Franco-German cultural broadcaster with 14+ million viewers. Arte is the primary European co-commissioner of documentary, art cinema and cultural programming. Pre-buys and co-produces around 30 feature-length documentaries and 10+ fiction films annually. Prioritises European co-productions.',
  null, 'Europe',
  '{"Documentary","Drama"}', '{"feature","documentary","series"}', '{"development","production"}', '{"French","German"}',
  100000, 2000000, null,
  null, 'https://www.arte.tv/en/about-arte/co-productions/', true,
  '{"second_film","established","veteran"}', 'medium',
  null, true, true, true,
  'coproductions@arte.tv', null, null, 'https://www.arte.tv/en/about-arte/co-productions/', 'Annual rounds — EFM and Cannes are primary pitching windows');
