-- ============================================================================
-- FYLYMPITCH - Migration 078: list public announcements for the sitemap
-- Run once in the Supabase SQL Editor. Tiny; depends on 077.
--
-- Migration 077 gave published announcements a public page. The sitemap then
-- needs to enumerate them - but admin_broadcasts is admin-only for select
-- (migration 063), and the sitemap is generated by an anonymous server client,
-- so a direct query returns nothing and the pages never get submitted to
-- Google. Widening the table's RLS would hand anon the sender id, the audience
-- and the recipient count along with it.
--
-- So: a SECURITY DEFINER function that returns only what a sitemap entry needs
-- - the slug and the two dates - and only for rows already published.
-- ============================================================================

create or replace function public.public_announcement_index()
returns table (
  public_slug text,
  created_at  timestamptz,
  edited_at   timestamptz
)
language sql security definer set search_path = public stable as $$
  select b.public_slug,
         b.created_at,
         (to_jsonb(b) ->> 'edited_at')::timestamptz
  from   public.admin_broadcasts b
  where  b.is_public
    and  b.public_slug is not null
    and  b.audience = 'all'
  order  by b.created_at desc
  limit  500;
$$;

revoke all on function public.public_announcement_index() from public;
grant execute on function public.public_announcement_index() to anon, authenticated;

-- Check: should list one row per published announcement.
-- select * from public.public_announcement_index();
